-- LGD Tail Extension: schema for Supabase Postgres.
-- Generated by scripts/make_migration.py from hazard_ext/web/models.py. Do not edit by hand.
--
-- The tables live in the private schema "hazard". Do NOT add this schema to the exposed
-- schemas of the Supabase Data API. Row-level security is enabled with no policies, so even
-- if it were exposed the anon and authenticated roles could read nothing. Only the app,
-- connecting with the database connection string, uses these tables.

create schema if not exists "hazard";

CREATE TABLE IF NOT EXISTS hazard.blobs (
	key VARCHAR(300) NOT NULL, 
	data BYTEA NOT NULL, 
	PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS hazard.users (
	id SERIAL NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	password_hash VARCHAR(300) NOT NULL, 
	is_admin BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	session_version INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_hazard_users_email ON hazard.users (email);

CREATE TABLE IF NOT EXISTS hazard.projects (
	id SERIAL NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	created_by INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(created_by) REFERENCES hazard.users (id)
);

CREATE TABLE IF NOT EXISTS hazard.agent_log (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	instruction TEXT NOT NULL, 
	reply TEXT NOT NULL, 
	proposals JSONB NOT NULL, 
	applied BOOLEAN NOT NULL, 
	applied_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES hazard.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES hazard.users (id)
);
CREATE INDEX IF NOT EXISTS ix_hazard_agent_log_project_id ON hazard.agent_log (project_id);

CREATE TABLE IF NOT EXISTS hazard.client_curves (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	label VARCHAR(100) NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	basis VARCHAR(20) NOT NULL, 
	values JSONB NOT NULL, 
	source_filename VARCHAR(300) NOT NULL, 
	uploaded_by INTEGER NOT NULL, 
	uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_curve_project_label_kind UNIQUE (project_id, label, kind), 
	FOREIGN KEY(project_id) REFERENCES hazard.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(uploaded_by) REFERENCES hazard.users (id)
);
CREATE INDEX IF NOT EXISTS ix_hazard_client_curves_project_id ON hazard.client_curves (project_id);

CREATE TABLE IF NOT EXISTS hazard.datasets (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	category VARCHAR(100) NOT NULL, 
	filename VARCHAR(300) NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	meta JSONB NOT NULL, 
	profile JSONB NOT NULL, 
	blob_key VARCHAR(300) NOT NULL, 
	uploaded_by INTEGER NOT NULL, 
	uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_dataset_project_sha UNIQUE (project_id, sha256), 
	FOREIGN KEY(project_id) REFERENCES hazard.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(uploaded_by) REFERENCES hazard.users (id)
);
CREATE INDEX IF NOT EXISTS ix_hazard_datasets_project_id ON hazard.datasets (project_id);

CREATE TABLE IF NOT EXISTS hazard.project_members (
	project_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	role VARCHAR(20) NOT NULL, 
	PRIMARY KEY (project_id, user_id), 
	FOREIGN KEY(project_id) REFERENCES hazard.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES hazard.users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hazard.scenarios (
	id SERIAL NOT NULL, 
	project_id INTEGER NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	params JSONB NOT NULL, 
	created_by INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_scenario_project_name UNIQUE (project_id, name), 
	FOREIGN KEY(project_id) REFERENCES hazard.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by) REFERENCES hazard.users (id)
);
CREATE INDEX IF NOT EXISTS ix_hazard_scenarios_project_id ON hazard.scenarios (project_id);

CREATE TABLE IF NOT EXISTS hazard.results (
	scenario_id INTEGER NOT NULL, 
	dataset_id INTEGER NOT NULL, 
	status VARCHAR(10) NOT NULL, 
	error TEXT NOT NULL, 
	stale BOOLEAN NOT NULL, 
	effective_params JSONB NOT NULL, 
	curve_label VARCHAR(100) NOT NULL, 
	summary JSONB NOT NULL, 
	payload JSONB NOT NULL, 
	computed_by INTEGER NOT NULL, 
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (scenario_id, dataset_id), 
	FOREIGN KEY(scenario_id) REFERENCES hazard.scenarios (id) ON DELETE CASCADE, 
	FOREIGN KEY(dataset_id) REFERENCES hazard.datasets (id) ON DELETE CASCADE, 
	FOREIGN KEY(computed_by) REFERENCES hazard.users (id)
);

CREATE TABLE IF NOT EXISTS hazard.scenario_overrides (
	scenario_id INTEGER NOT NULL, 
	dataset_id INTEGER NOT NULL, 
	params JSONB NOT NULL, 
	PRIMARY KEY (scenario_id, dataset_id), 
	FOREIGN KEY(scenario_id) REFERENCES hazard.scenarios (id) ON DELETE CASCADE, 
	FOREIGN KEY(dataset_id) REFERENCES hazard.datasets (id) ON DELETE CASCADE
);

alter table "hazard"."blobs" enable row level security;
alter table "hazard"."users" enable row level security;
alter table "hazard"."projects" enable row level security;
alter table "hazard"."agent_log" enable row level security;
alter table "hazard"."client_curves" enable row level security;
alter table "hazard"."datasets" enable row level security;
alter table "hazard"."project_members" enable row level security;
alter table "hazard"."scenarios" enable row level security;
alter table "hazard"."results" enable row level security;
alter table "hazard"."scenario_overrides" enable row level security;

revoke all on schema "hazard" from anon, authenticated;
revoke all on all tables in schema "hazard" from anon, authenticated;
