"""Write migrations/001_init.sql from the ORM models (Postgres dialect).

The app creates the same objects itself at start-up when AUTO_CREATE_SCHEMA is true; this
file is for running the schema by hand in the Supabase SQL editor instead.

Usage:  python scripts/make_migration.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from hazard_ext.web.models import SCHEMA, Base

OUT = Path(__file__).resolve().parents[1] / "migrations" / "001_init.sql"


def main() -> None:
    dialect = postgresql.dialect()
    parts = [
        "-- LGD Tail Extension: schema for Supabase Postgres.",
        "-- Generated by scripts/make_migration.py from hazard_ext/web/models.py. Do not edit by hand.",
        "--",
        f"-- The tables live in the private schema \"{SCHEMA}\". Do NOT add this schema to the exposed",
        "-- schemas of the Supabase Data API. Row-level security is enabled with no policies, so even",
        "-- if it were exposed the anon and authenticated roles could read nothing. Only the app,",
        "-- connecting with the database connection string, uses these tables.",
        "",
        f'create schema if not exists "{SCHEMA}";',
        "",
    ]
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table, if_not_exists=True).compile(dialect=dialect)).strip()
        parts.append(ddl + ";")
        for index in sorted(table.indexes, key=lambda i: i.name):
            parts.append(str(CreateIndex(index, if_not_exists=True).compile(dialect=dialect)).strip() + ";")
        parts.append("")
    for table in Base.metadata.sorted_tables:
        parts.append(f'alter table "{SCHEMA}"."{table.name}" enable row level security;')
    parts += [
        "",
        f'revoke all on schema "{SCHEMA}" from anon, authenticated;',
        f'revoke all on all tables in schema "{SCHEMA}" from anon, authenticated;',
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({len(Base.metadata.sorted_tables)} tables)")


if __name__ == "__main__":
    main()
